### PR TITLE
Change React.PropTypes to just PropTypes

### PR DESCRIPTION
**Pull request by brownieboy**
Fix for issue #28, now that React.PropTypes no longer works in React 15.5 or higher.  PropTypes have been moved to their own package.

### CODE REVIEW

**Review by xtuc — APPROVED** [review]
thanks for your pr

**Comment by brownieboy** [comment]
Thanks for the merge.

So how do we get the changes onto https://packagecontrol.io/ ?

**Comment by xtuc** [comment]
I'm new to this sorry, I think we need to do a git tag on this repo.

I can look into it tomorrow again.

**Comment by xtuc** [comment]
I did a release https://github.com/babel/babel-sublime-snippets/releases/tag/v1.0.7. It will update anytime soon on packagecontrol, could you maybe try on your side?

**Comment by brownieboy** [comment]
Cool.  I'll keep a look out for that.

**Comment by brownieboy** [comment]
And we have lift off!!

It now shows as 1.0.7 at  https://packagecontrol.io/packages/Babel%20Snippets, and it updated in my own setup just now.

**Comment by xtuc** [comment]
Cool, thanks for the confirmation.

**Pull request merged**
