### PR TITLE
Correct spelling error in README.

### PR DESCRIPTION
**Pull request by Cheerazar**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Thanks

**Comment by zertosh** [comment]
hey @thejameskyle next time also push a new tag with a version bump so that Package Control updates :)

**Comment by sebmck** [comment]
@thejameskyle Don't touchie repos that aren't yours :stuck_out_tongue:

**Comment by zertosh** [comment]
No no, you guys are totally welcomed here :smile:

**Comment by thejameskyle** [comment]
You want a version bump for a README change? Why?

**Comment by zertosh** [comment]
So that the README at https://packagecontrol.io/packages/Babel%20Snippets also has the corrections

**Pull request merged**
